background_opacity 0.7

# Use the splits layout so vsplit/hsplit directions are respected
enabled_layouts splits

# Feature 1: New windows/tabs open in the same directory as the current one
map ctrl+shift+enter launch --cwd=current
map ctrl+shift+t     launch --cwd=current --type=tab

# Feature 2: Manage multiple terminal instances within the same window
# Splits
map ctrl+shift+o launch --cwd=current --location=vsplit
map ctrl+shift+e launch --cwd=current --location=hsplit

# Navigate between splits
map ctrl+alt+h neighboring_window left
map ctrl+alt+l neighboring_window right
map ctrl+alt+k neighboring_window up
map ctrl+alt+j neighboring_window down

# Resize splits
map ctrl+alt+shift+h resize_window narrower 3
map ctrl+alt+shift+l resize_window wider 3
map ctrl+alt+shift+k resize_window taller 3
map ctrl+alt+shift+j resize_window shorter 3

# Navigate between tabs
map ctrl+shift+l next_tab
map ctrl+shift+h  previous_tab
