-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'listener {' on line 7

-- TODO: manual review — unknown section 'listener {' on line 20

-- TODO: manual review — unknown section 'listener {' on line 25

hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock", -- avoid starting multiple hyprlock instances.
        before_sleep_cmd = "loginctl lock-session", -- lock before suspend.
        after_sleep_cmd = "hyprctl dispatch dpms on", -- to avoid having to press a key twice to turn on the display.
    },
    -- turn off keyboard backlight, comment out this section if you dont have a keyboard backlight.
    -- listener { 
    --     timeout = 150                                          # 2.5min.
    --     on-timeout = brightnessctl -sd rgb:kbd_backlight set 0 # turn off keyboard backlight.
    --     on-resume = brightnessctl -rd rgb:kbd_backlight        # turn on keyboard backlight.
    -- }
    -- listener {
    --     timeout = 3600                                # 60min
    --     on-timeout = systemctl suspend                # suspend pc
    -- }
})

