-- BACKGROUND
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'background {' on line 2
-- contrast = 1
-- brightness = 1

-- GENERAL

-- TODO: manual review — unknown section 'input-field {' on line 23

-- TODO: manual review — unknown section 'label {' on line 48

-- TODO: manual review — unknown section 'label {' on line 60
hl.config({
    general = {
        no_fade_in = false,
        no_fade_out = false,
        hide_cursor = true,
        grace = 0,
        disable_loading_bar = true,
        ignore_empty_input = true,
    },
    -- INPUT FIELD
    -- DATE
    -- TIME
})

