-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — top-level key 'splash = false' has no enclosing section
-- TODO: manual review — top-level key 'ipc = true' has no enclosing section
